name: Shotbyrichie
favicon: null
layout_spectrum: 0.5047869614791125
typography_spectrum: 0.9483664291910827
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6008182077202946
  lightness: 0.9536202880553901
  saturation: 0.5430025642272085
  rhythmicContrast: 0.4915066787507385
purpose: []
